name: CI MLflow Training

on:
  push:
    branches: ["main"]

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Micromamba (Conda alternative)
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: MLProject/conda.yaml
          init-shell: bash

      - name: Install dependencies
        run: |
          pip install mlflow

      - name: Run MLflow Project
        run: |
          cd MLProject
          mlflow run .
