name: CI MLflow Training

on:
  push:
    branches: ["main"]

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.10
          auto-update-conda: true

      - name: Install dependencies
        run: |
          pip install mlflow

      - name: Run MLflow Project
        run: |
          cd MLProject
          mlflow run .
